name: Our CD

on: 
  release:
    types:
      - published

job:
  build: # must run before publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Build Package
        run: pipx run build # github has things installed already including python
      - uses: actions/upload-artifact@v3
        with:
          path: dist/* # upload everything in dist directory to some directory; can then be used for other steps

  publish: # job depending on build job 
    needs: [build] # runs after build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/wintersession2024cicd
    permissions:
      id-token: write
    steps: 
     - uses: actions/download-artifact@v3
       with:
         name: artifact
         path: dist
     -uses: pypa/gh-action-pypi-publish@release/v1
       with: 
         repository-url: https:test.pypi.org/legacy/