name: Our CI

on: 
  pull_request: 
  push:
    - main
    - other-branch
  workflow_dispatch: # adds button to click to run manually

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hello world"
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      -name: Install Python Module
        run: python -m pip install .[]
